// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8bHyaIyyIWwowbGdX6cXZwt1-VcLF0E',
    appId: '1:328017867857:web:4dee2ec8727430031d7470',
    messagingSenderId: '328017867857',
    projectId: 'flutterfirebase2024-3088f',
    authDomain: 'flutterfirebase2024-3088f.firebaseapp.com',
    storageBucket: 'flutterfirebase2024-3088f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaVsNjy1c01TiZybOBzN1NB-M_vDr-lEs',
    appId: '1:328017867857:android:4837fd8a671ee1a01d7470',
    messagingSenderId: '328017867857',
    projectId: 'flutterfirebase2024-3088f',
    storageBucket: 'flutterfirebase2024-3088f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr08aNMS3_g8clrnLC2quA7kyXIGsigCw',
    appId: '1:328017867857:ios:fd4fbfeb056768551d7470',
    messagingSenderId: '328017867857',
    projectId: 'flutterfirebase2024-3088f',
    storageBucket: 'flutterfirebase2024-3088f.appspot.com',
    iosBundleId: 'app.meedu.flutterFirebase2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr08aNMS3_g8clrnLC2quA7kyXIGsigCw',
    appId: '1:328017867857:ios:e9845c487114e55d1d7470',
    messagingSenderId: '328017867857',
    projectId: 'flutterfirebase2024-3088f',
    storageBucket: 'flutterfirebase2024-3088f.appspot.com',
    iosBundleId: 'app.meedu.flutterFirebase2024.RunnerTests',
  );
}
